"""empty message

Revision ID: e66bc61a3cdc
Revises: 
Create Date: 2021-05-20 03:17:38.494207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66bc61a3cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=64), nullable=True),
    sa.Column('form_of_contact', sa.String(length=64), nullable=True),
    sa.Column('form_of_payment', sa.String(length=64), nullable=True),
    sa.Column('donation_frequency', sa.String(length=64), nullable=True),
    sa.Column('donation_amount', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
